### PR TITLE
Fix app name in build script

### PR DESCRIPTION
**Pull request by cbenhagen**

### CODE REVIEW

**Comment by DanTup** [comment]
@cbenhagen did you need to change this for it to work on your machine? It worked as-is on mine which seems odd. I'm not on that machien atm, but I'll test with this change later and as long as it still works there I'll merge. If not, we'll have to figure out what's different 😄

**Comment by cbenhagen** [comment]
Yes, I had to change it. Maybe you have an older version of the app? I have version `6.0.2`.

**Comment by DanTup** [comment]
This didn't work for me:

```
danny@Dannys-MacBook-Pro ~ % open -a "Elgato Stream Deck"
Unable to find application named 'Elgato Stream Deck'
```

However I noticed I was on v5. After accepting the v6 update, I saw `Stream Deck.app` in my applications folder was replaced by `Elgato Stream Deck.app`. So apparently it did change, and this is the correct/new name. Thanks!

**Comment by cbenhagen** [comment]
Maybe an even better fix would have been to open the app using the bundle id with:
`open -b com.elgato.StreamDeck`

Not sure if this will ever become a problem again though..

**Comment by DanTup** [comment]
Ah, I didn't know that was possible. That probably mades more sense because it handles both versions (and any future renames). I've updated it in c14e6f9d4d538ef38d49af4a327b94feaaa6575f. Thanks!

**Pull request merged**
