### PR TITLE
Add image example

### PR DESCRIPTION
**Pull request by cbenhagen**
Todo:
- [x] Add links to readme
- [ ] Maybe find some more interesting things we can show in this example

### CODE REVIEW

**Comment by cbenhagen** [comment]
Rebased

**Comment by DanTup** [comment]
(haven't forgotten about this, just haven't had the chance to check it out and take a proper look - will try to get to it this week!)

**Comment by DanTup** [comment]
Sorry for the delay. This looks reasonable to me - if you add the links to the readme I'll merge it.

(I should also publish a release, since there are some fixes that still haven't been published!)

**Review by DanTup — APPROVED** [review]

**Comment by cbenhagen** [comment]
No worries. Links have been added.

**Comment by DanTup** [comment]
Thanks!

**Pull request merged**
