### PR TITLE
Adds missing event handlers

### PR DESCRIPTION
**Pull request by ChekTek**
Added the settings, global settings, application launched, and application terminated events to the socket event handler.

### CODE REVIEW

**Review by DanTup — APPROVED** [review]
Oops, good catch(es)! 🙈 Thanks!

I'd like to code-gen a lot of this to avoid mistakes like this, but my plan was to get things working first so I knew exactly what I needed to generate. IRL stuff has gotten in the way a little lately though.

Thanks!

**Comment by ChekTek** [comment]
No worries! 😁 I was building my own Stream Deck library in Dart, but when I saw yours it looked like a better way to do it (I'm somewhat new to Dart). I'm using this to build a side project plugin soon, so if I run into anything else I will create another pull request. 👍

**Comment by DanTup** [comment]
Cool, thanks!

Right now the process of building and installing plugins is a bit clusmy, but one thing I was hoping to try and get working is debugging and hot reload, so you can easily debug code (using breakpoints, etc.) while interacting via the StreamDeck, and make changes without needing to go through a compile/reploy/restart-stream-deck cycle.

I also have some very basic Property Inspector interaction work (eg. you can write the client-side PI scripts also in Dart, which compile to JS). It's currently (incomplete) in another plugin project I'm working on, but I'd like to generalise it and move it into here so Dart can be used for both sides.

**Comment by DanTup** [comment]
Sorry for the long delay.. I've published 0.3.0 with all the recently made changes. Thanks!

**Pull request merged**
